// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    MotActionSheet: typeof import('./components/actionsheet/actionsheet.vue')['default']
    MotAddress: typeof import('./components/address/address.vue')['default']
    MotAddressList: typeof import('./components/addresslist/addresslist.vue')['default']
    MotAnimate: typeof import('./components/animate/animate.vue')['default']
    MotAvatar: typeof import('./components/avatar/avatar.vue')['default']
    MotAvatarGroup: typeof import('./components/avatargroup/avatargroup.vue')['default']
    MotBacktop: typeof import('./components/backtop/backtop.vue')['default']
    MotBadge: typeof import('./components/badge/badge.vue')['default']
    MotBarrage: typeof import('./components/barrage/barrage.vue')['default']
    MotButton: typeof import('./components/button/button.vue')['default']
    MotCalendar: typeof import('./components/calendar/calendar.vue')['default']
    MotCard: typeof import('./components/card/card.vue')['default']
    MotCascader: typeof import('./components/cascader/cascader.vue')['default']
    MotCategory: typeof import('./components/category/category.vue')['default']
    MotCategoryPane: typeof import('./components/categorypane/categorypane.vue')['default']
    MotCell: typeof import('./components/cell/cell.vue')['default']
    MotCellGroup: typeof import('./components/cellgroup/cellgroup.vue')['default']
    MotCheckbox: typeof import('./components/checkbox/checkbox.vue')['default']
    MotCheckboxGroup: typeof import('./components/checkboxgroup/checkboxgroup.vue')['default']
    MotCircleProgress: typeof import('./components/circleprogress/circleprogress.vue')['default']
    MotCol: typeof import('./components/col/col.vue')['default']
    MotCollapse: typeof import('./components/collapse/collapse.vue')['default']
    MotCollapseItem: typeof import('./components/collapseitem/collapseitem.vue')['default']
    MotComment: typeof import('./components/comment/comment.vue')['default']
    MotConfigProvider: typeof import('./components/configprovider/configprovider.vue')['default']
    MotCountdown: typeof import('./components/countdown/countdown.vue')['default']
    MotCountup: typeof import('./components/countup/countup.vue')['default']
    MotDatePicker: typeof import('./components/datepicker/datepicker.vue')['default']
    MotDialog: typeof import('./components/dialog/dialog.vue')['default']
    MotDivider: typeof import('./components/divider/divider.vue')['default']
    MotDrag: typeof import('./components/drag/drag.vue')['default']
    MotEcard: typeof import('./components/ecard/ecard.vue')['default']
    MotElevator: typeof import('./components/elevator/elevator.vue')['default']
    MotEllipsis: typeof import('./components/ellipsis/ellipsis.vue')['default']
    MotEmpty: typeof import('./components/empty/empty.vue')['default']
    MotFixedNav: typeof import('./components/fixednav/fixednav.vue')['default']
    MotForm: typeof import('./components/form/form.vue')['default']
    MotFormItem: typeof import('./components/formitem/formitem.vue')['default']
    MotGrid: typeof import('./components/grid/grid.vue')['default']
    MotGridItem: typeof import('./components/griditem/griditem.vue')['default']
    MotIcon: typeof import('./components/icon/icon.vue')['default']
    MotImagePreview: typeof import('./components/imagepreview/imagepreview.vue')['default']
    MotIndicator: typeof import('./components/indicator/indicator.vue')['default']
    MotInfiniteloading: typeof import('./components/infiniteloading/infiniteloading.vue')['default']
    MotInput: typeof import('./components/input/input.vue')['default']
    MotInputNumber: typeof import('./components/inputnumber/inputnumber.vue')['default']
    MotInvoice: typeof import('./components/invoice/invoice.vue')['default']
    MotList: typeof import('./components/list/list.vue')['default']
    MotMenu: typeof import('./components/menu/menu.vue')['default']
    MotMenuItem: typeof import('./components/menuitem/menuitem.vue')['default']
    MotNavbar: typeof import('./components/navbar/navbar.vue')['default']
    MotNoticebar: typeof import('./components/noticebar/noticebar.vue')['default']
    MotNotify: typeof import('./components/notify/notify.vue')['default']
    MotNumberKeyboard: typeof import('./components/numberkeyboard/numberkeyboard.vue')['default']
    MotOverlay: typeof import('./components/overlay/overlay.vue')['default']
    MotPagination: typeof import('./components/pagination/pagination.vue')['default']
    MotPicker: typeof import('./components/picker/picker.vue')['default']
    MotPopover: typeof import('./components/popover/popover.vue')['default']
    MotPopup: typeof import('./components/popup/popup.vue')['default']
    MotPrice: typeof import('./components/price/price.vue')['default']
    MotProgress: typeof import('./components/progress/progress.vue')['default']
    MotRadio: typeof import('./components/radio/radio.vue')['default']
    MotRadioGroup: typeof import('./components/radiogroup/radiogroup.vue')['default']
    MotRange: typeof import('./components/range/range.vue')['default']
    MotRate: typeof import('./components/rate/rate.vue')['default']
    MotRow: typeof import('./components/row/row.vue')['default']
    MotSearchbar: typeof import('./components/searchbar/searchbar.vue')['default']
    MotShortPassword: typeof import('./components/shortpassword/shortpassword.vue')['default']
    MotSideNavbar: typeof import('./components/sidenavbar/sidenavbar.vue')['default']
    MotSideNavbaritem: typeof import('./components/sidenavbaritem/sidenavbaritem.vue')['default']
    MotSideNavbarItem: typeof import('./components/sidenavbaritem/sidenavbaritem.vue')['default']
    MotSignature: typeof import('./components/signature/signature.vue')['default']
    MotSkeleton: typeof import('./components/skeleton/skeleton.vue')['default']
    MotSku: typeof import('./components/sku/sku.vue')['default']
    MotSkuHeader: typeof import('./components/skuheader/skuheader.vue')['default']
    MotSkuOperate: typeof import('./components/skuoperate/skuoperate.vue')['default']
    MotStep: typeof import('./components/step/step.vue')['default']
    MotSteps: typeof import('./components/steps/steps.vue')['default']
    MotSticky: typeof import('./components/sticky/sticky.vue')['default']
    MotSubsideNavbar: typeof import('./components/subsidenavbar/subsidenavbar.vue')['default']
    MotSubSideNavbar: typeof import('./components/subsidenavbar/subsidenavbar.vue')['default']
    MotSwipe: typeof import('./components/swipe/swipe.vue')['default']
    MotSwiper: typeof import('./components/swiper/swiper.vue')['default']
    MotSwiperItem: typeof import('./components/swiperitem/swiperitem.vue')['default']
    MotSwitch: typeof import('./components/switch/switch.vue')['default']
    MotTabbar: typeof import('./components/tabbar/tabbar.vue')['default']
    MotTabbarItem: typeof import('./components/tabbaritem/tabbaritem.vue')['default']
    MotTable: typeof import('./components/table/table.vue')['default']
    MotTabPane: typeof import('./components/tabpane/tabpane.vue')['default']
    MotTabs: typeof import('./components/tabs/tabs.vue')['default']
    MotTag: typeof import('./components/tag/tag.vue')['default']
    MotTextarea: typeof import('./components/textarea/textarea.vue')['default']
    MotTimeDetail: typeof import('./components/timedetail/timedetail.vue')['default']
    MotTimePannel: typeof import('./components/timepannel/timepannel.vue')['default']
    MotTimeSelect: typeof import('./components/timeselect/timeselect.vue')['default']
    MotToast: typeof import('./components/toast/toast.vue')['default']
    MotTour: typeof import('./components/tour/tour.vue')['default']
    MotTransition: typeof import('./components/transition/transition.vue')['default']
    MotTrendArrow: typeof import('./components/trendarrow/trendarrow.vue')['default']
    MotUploader: typeof import('./components/uploader/uploader.vue')['default']
    MotWatermark: typeof import('./components/watermark/watermark.vue')['default']
    MotCodeInput: typeof import('./components/codeinput/codeinput.vue')['default']
    MotDollMachine: typeof import('./components/dollmachine/dollmachine.vue')['default']
    MotGiftBox: typeof import('./components/giftbox/giftbox.vue')['default']
    MotHitEggs: typeof import('./components/hiteggs/hiteggs.vue')['default']
    MotMarquee: typeof import('./components/marquee/marquee.vue')['default']
    MotShakeDice: typeof import('./components/shakedice/shakedice.vue')['default']
    MotTurnTable: typeof import('./components/turntable/turntable.vue')['default']
    MotLoadingPage: typeof import('./components/loadingpage/loadingpage.vue')['default']

  }

  // interface ComponentCustomProperties {}
}

export { }
