export const components = [
  {
    text: '基础组件',
    collapsed: false,
    items: [
      { text: 'Button 按钮', link: '/components/button' },
      { text: 'Cell 单元格', link: '/components/cell' },
      { text: 'ConfigProvider 全局配置', link: '/components/configprovider' },
      { text: 'Icon 图标', link: '/components/icon' },
      { text: 'Overlay 遮照层', link: '/components/overlay' },
      { text: 'Popup 弹出层', link: '/components/popup' },
      { text: 'Transition 过渡', link: '/components/transition' },
    ],
    type: 'basic',
  },
  {
    text: '布局组件',
    collapsed: false,
    items: [
      { text: 'Divider 分割线', link: '/components/divider' },
      { text: 'Grid 宫格', link: '/components/grid' },
      { text: 'Layout 布局', link: '/components/layout' },
      { text: 'SafeArea 安全区', link: '/components/safearea' },
      { text: 'Sticky 粘性布局', link: '/components/sticky' },
    ],
    type: 'layout',
  },
  {
    text: '导航组件',
    collapsed: false,
    items: [
      { text: 'Elevator 电梯楼层', link: '/components/elevator' },
      { text: 'FixedNav 悬浮导航', link: '/components/fixednav' },
      { text: 'Indicator 指示器', link: '/components/indicator' },
      { text: 'Menu 菜单', link: '/components/menu' },
      { text: 'Navbar 头部导航', link: '/components/navbar' },
      { text: 'Pagination 分页', link: '/components/pagination' },
      { text: 'SideNavbar 侧边栏导航', link: '/components/sidenavbar' },
      { text: 'Tabbar 标签栏', link: '/components/tabbar' },
      { text: 'Tabs 选项卡切换', link: '/components/tabs' },

    ],
    type: 'nav',
  },
  {
    text: '数据录入',
    collapsed: false,
    items: [
      { text: 'Calendar 日历', link: '/components/calendar' },
      { text: 'Cascader 级联选择器', link: '/components/cascader' },
      { text: 'Checkbox 复选按钮', link: '/components/checkbox' },
      { text: 'DatePicker 日期选择器', link: '/components/datepicker' },
      { text: 'Form 表单', link: '/components/form' },
      { text: 'Input 输入框', link: '/components/input' },
      { text: 'InputNumber 数字输入框', link: '/components/inputnumber' },
      { text: 'CodeInput 验证码输入框', link: '/components/codeinput' },
      { text: 'NumberKeyboard 数字键盘', link: '/components/numberkeyboard' },
      { text: 'Picker 选择器', link: '/components/picker' },
      { text: 'Radio 单选按钮', link: '/components/radio' },
      { text: 'Range 区间选择器', link: '/components/range' },
      { text: 'Rate 评分', link: '/components/rate' },
      { text: 'Searchbar 搜索栏', link: '/components/searchbar' },
      { text: 'ShortPassword 短密码', link: '/components/shortpassword' },
      { text: 'Textarea 文本域', link: '/components/textarea' },
      { text: 'Uploader 上传', link: '/components/uploader' },

    ],
    type: 'dentry',
  },
  {
    text: '操作反馈',
    collapsed: false,
    items: [
      { text: 'ActionSheet 动作面板', link: '/components/actionsheet' },
      { text: 'Backtop 返回顶部', link: '/components/backtop' },
      { text: 'Dialog 对话框', link: '/components/dialog' },
      { text: 'Drag 拖拽', link: '/components/drag' },
      { text: 'Notify 消息通知', link: '/components/notify' },
      { text: 'Swipe 滑动手势', link: '/components/swipe' },
      { text: 'Switch 开关', link: '/components/switch' },
      { text: 'Toast 吐司', link: '/components/toast' },

    ],
    type: 'feedback',
  },
  {
    text: '展示组件',
    collapsed: false,
    items: [
      { text: 'Animate 动画/动效', link: '/components/animate' },
      { text: 'Avatar 头像', link: '/components/avatar' },
      { text: 'Badge 徽标', link: '/components/badge' },
      { text: 'CircleProgress 环形进度条', link: '/components/circleprogress' },
      { text: 'Collapse 折叠面板', link: '/components/collapse' },
      { text: 'Countdown 倒计时', link: '/components/countdown' },
      { text: 'Countup 数字滚动', link: '/components/countup' },
      { text: 'Ellipsis 文本省略', link: '/components/ellipsis' },
      { text: 'Empty 空状态', link: '/components/empty' },
      { text: 'ImagePreview 图片预览', link: '/components/imagepreview' },
      { text: 'List 虚拟列表', link: '/components/list' },
      { text: 'LoadingPage 加载页', link: '/components/loadingpage' },
      { text: 'Noticebar 公告栏', link: '/components/noticebar' },
      { text: 'Popover 气泡弹出框', link: '/components/popover' },
      { text: 'Price 价格', link: '/components/price' },
      { text: 'Progress 进度条', link: '/components/progress' },
      { text: 'Skeleton 骨架屏', link: '/components/skeleton' },
      { text: 'Steps 步骤条', link: '/components/steps' },
      { text: 'Swiper 轮播', link: '/components/swiper' },
      { text: 'Table 表格', link: '/components/table' },
      { text: 'Tag 标签', link: '/components/tag' },
      // { text: 'Tour 引导', link: '/components/tour' },
      { text: 'TrendArrow 趋势箭头', link: '/components/trendarrow' },
      { text: 'Watermark 水印', link: '/components/watermark' },
    ],
    type: 'exhibition',
  },
  {
    text: '特色组件',
    collapsed: false,
    items: [
      { text: 'Address 地址', link: '/components/address' },
      { text: 'AddressList 地址列表', link: '/components/addresslist' },
      { text: 'Barrage 弹幕', link: '/components/barrage' },
      { text: 'Card 商品卡片', link: '/components/card' },
      { text: 'Category 商品分类', link: '/components/category' },
      { text: 'Comment 商品评论', link: '/components/comment' },
      { text: 'Ecard 虚拟电子卡', link: '/components/ecard' },
      { text: 'Invoice 发票', link: '/components/invoice' },
      { text: 'Signature 签名', link: '/components/signature' },
      { text: 'Sku 商品规格选择', link: '/components/sku' },
      { text: 'TimeSelect 配送时间', link: '/components/timeselect' },
    ],
    type: 'business',
  },
  {
    text: '抽奖组件',
    collapsed: false,
    items: [
      { text: 'TurnTable 大转盘抽奖', link: '/components/turntable' },
      { text: 'Marquee 跑马灯抽奖', link: '/components/marquee' },
      { text: 'GiftBox 神秘大礼盒', link: '/components/giftbox' },
      { text: 'Hiteggs 砸金蛋', link: '/components/hiteggs' },
      { text: 'DollMachine 抓娃娃机', link: '/components/dollmachine' },
      { text: 'ShakeDice 摇骰子', link: '/components/shakedice' },
    ],
    type: 'bingo',
  },
]

export const navComponents = components.map(i => ({ text: i.text, link: i.items[0].link, type: i.type }))

export const sidebarComponents: any[] = components.reduce((acc, cur: any) => {
  return acc.concat(cur.items.map((i: any) => ({ ...i, type: cur.type })))
}, [])

export const guides = [
  { text: '概览', link: '/guide/overview' },
  { text: '快速上手', link: '/guide/quick-start' },
  { text: 'vscode 插件支持', link: '/guide/vscode-extension' },
  { text: '国际化', link: '/guide/i18n' },
  { text: '定制主题', link: '/guide/theme' },
  { text: '更新日志', link: '/guide/changelog' },
]
